### ISSUE TITLE
ModuleNotFoundError: No module named 'pygoogletranslation'

### ISSUE THREAD

**Issue by ZmeyGer** [hyd998877/stable-diffusion-webui-auto-translate-language#10]
init TpTranslate
Error loading script: trans_google.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-auto-translate-language\scripts\trans_google.py", line 2, in <module>
    from pygoogletranslation import Translator
ModuleNotFoundError: No module named 'pygoogletranslation'

**Comment by chekun** [comment]
same here even if manully `pip install pygoogletranslation`

**Comment by schoenid** [comment]
Same to me with:
![image](https://github.com/hyd998877/stable-diffusion-webui-auto-translate-language/assets/15383666/0adae231-221a-4748-b3e9-48b48becfb1a)

The module is not working.
(That's the reason I've disabled it ...)
